### ISSUE TITLE
Suggestion: Presets

### ISSUE THREAD

**Issue by MalMC** [pyroclient/pyro#144] opened 2020-08-10 02:53 UTC
we can customize our settings depending on what server we are playing on so we dont always have to change settings when we join a different server to optimize for that server

**Comment by Tri-tan** [comment] 2020-08-11 18:05
i wrte this exact suggestion but more detailed like 4h before you

read if some1 suggested the same tihing be4 u

**Comment by Artamedes** [comment] 2020-08-12 08:10
Duplicate of #141

**Closed by Artamedes** 2020-08-12 08:10 UTC
